import 'bloc/android_saatd_zenle_g_nderildi_bloc.dart';import 'models/android_saatd_zenle_g_nderildi_model.dart';import 'package:flutter/material.dart';import 'package:smart_watch_control/core/app_export.dart';import 'package:smart_watch_control/widgets/app_bar/appbar_leading_image.dart';import 'package:smart_watch_control/widgets/app_bar/appbar_trailing_circleimage.dart';import 'package:smart_watch_control/widgets/app_bar/custom_app_bar.dart';import 'package:smart_watch_control/widgets/custom_elevated_button.dart';import 'package:smart_watch_control/widgets/custom_text_form_field.dart';class AndroidSaatdZenleGNderildiScreen extends StatelessWidget {const AndroidSaatdZenleGNderildiScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<AndroidSaatdZenleGNderildiBloc>(create: (context) => AndroidSaatdZenleGNderildiBloc(AndroidSaatdZenleGNderildiState(androidSaatdZenleGNderildiModelObj: AndroidSaatdZenleGNderildiModel()))..add(AndroidSaatdZenleGNderildiInitialEvent()), child: AndroidSaatdZenleGNderildiScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: SizedBox(width: double.maxFinite, child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(height: 5.v), _buildStack(context), Container(padding: EdgeInsets.symmetric(horizontal: 27.h, vertical: 52.v), child: Column(children: [Text("msg_saat_kodu_d_zenle2".tr, style: theme.textTheme.headlineLarge), SizedBox(height: 52.v), BlocSelector<AndroidSaatdZenleGNderildiBloc, AndroidSaatdZenleGNderildiState, TextEditingController?>(selector: (state) => state.serialNumberController, builder: (context, serialNumberController) {return CustomTextFormField(controller: serialNumberController, hintText: "lbl_a362bsus725".tr, textInputAction: TextInputAction.done);}), SizedBox(height: 80.v), CustomElevatedButton(text: "lbl_ba_lant_g_nder".tr, margin: EdgeInsets.only(left: 41.h, right: 40.h), buttonStyle: CustomButtonStyles.none, decoration: CustomButtonStyles.gradientPrimaryToTealDecoration), SizedBox(height: 94.v), CustomImageView(imagePath: ImageConstant.imgSuccess, height: 25.v, width: 80.h, alignment: Alignment.centerLeft, margin: EdgeInsets.only(left: 100.h), onTap: () {onTapImgSuccess(context);}), SizedBox(height: 5.v)]))])))); } 
/// Section Widget
Widget _buildStack(BuildContext context) { return Container(height: 123.v, width: 333.h, margin: EdgeInsets.only(left: 7.h), child: Stack(alignment: Alignment.topCenter, children: [CustomImageView(imagePath: ImageConstant.imgLogo90x106, height: 90.v, width: 106.h, radius: BorderRadius.circular(45.h), alignment: Alignment.bottomCenter), CustomAppBar(height: 41.v, leadingWidth: 49.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgSend, margin: EdgeInsets.only(left: 7.h, bottom: 2.v), onTap: () {onTapSend(context);}), actions: [AppbarTrailingCircleimage(imagePath: ImageConstant.imgLogo30x35, margin: EdgeInsets.only(left: 20.h, top: 11.v, right: 20.h), onTap: () {onTapLogo(context);})])])); } 
/// Navigates to the ayarlarSayfasBildirimlerAKOneScreen when the action is triggered.
onTapSend(BuildContext context) { NavigatorService.pushNamed(AppRoutes.ayarlarSayfasBildirimlerAKOneScreen, ); } 
/// Navigates to the homeTwoScreen when the action is triggered.
onTapLogo(BuildContext context) { NavigatorService.pushNamed(AppRoutes.homeTwoScreen, ); } 
/// Navigates to the homeScreen when the action is triggered.
onTapImgSuccess(BuildContext context) { NavigatorService.pushNamed(AppRoutes.homeScreen, ); } 
 }
