import 'bloc/android_sifred_zenle_kaydet_bloc.dart';import 'models/android_sifred_zenle_kaydet_model.dart';import 'package:flutter/material.dart';import 'package:smart_watch_control/core/app_export.dart';import 'package:smart_watch_control/widgets/app_bar/appbar_leading_image.dart';import 'package:smart_watch_control/widgets/app_bar/appbar_trailing_circleimage.dart';import 'package:smart_watch_control/widgets/app_bar/custom_app_bar.dart';import 'package:smart_watch_control/widgets/custom_elevated_button.dart';import 'package:smart_watch_control/widgets/custom_text_form_field.dart';class AndroidSifredZenleKaydetScreen extends StatelessWidget {const AndroidSifredZenleKaydetScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<AndroidSifredZenleKaydetBloc>(create: (context) => AndroidSifredZenleKaydetBloc(AndroidSifredZenleKaydetState(androidSifredZenleKaydetModelObj: AndroidSifredZenleKaydetModel()))..add(AndroidSifredZenleKaydetInitialEvent()), child: AndroidSifredZenleKaydetScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 16.h), child: Column(children: [CustomImageView(imagePath: ImageConstant.imgLogo90x106, height: 90.v, width: 106.h, radius: BorderRadius.circular(45.h)), SizedBox(height: 27.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 73.h), child: Text("lbl_ifre_yenile".tr, style: theme.textTheme.headlineLarge))), SizedBox(height: 19.v), _buildOldPassword(context), SizedBox(height: 39.v), _buildNewPassword(context), SizedBox(height: 24.v), _buildConfirmNewPassword(context), SizedBox(height: 39.v), Padding(padding: EdgeInsets.symmetric(horizontal: 23.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [_buildSifremiUnuttum(context), _buildKaydet(context)])), SizedBox(height: 39.v), CustomImageView(imagePath: ImageConstant.imgSuccess, height: 25.v, width: 80.h, onTap: () {onTapImgSuccess(context);}), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 46.v, leadingWidth: 49.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgSend, margin: EdgeInsets.only(left: 7.h, top: 2.v, bottom: 2.v), onTap: () {onTapSend(context);}), actions: [AppbarTrailingCircleimage(imagePath: ImageConstant.imgLogo30x35, margin: EdgeInsets.fromLTRB(10.h, 2.v, 10.h, 11.v), onTap: () {onTapLogo(context);})]); } 
/// Section Widget
Widget _buildOldPassword(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 12.h, right: 11.h), child: BlocSelector<AndroidSifredZenleKaydetBloc, AndroidSifredZenleKaydetState, TextEditingController?>(selector: (state) => state.oldPasswordController, builder: (context, oldPasswordController) {return CustomTextFormField(controller: oldPasswordController, hintText: "lbl_eski_ifre".tr);})); } 
/// Section Widget
Widget _buildNewPassword(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 16.h, right: 7.h), child: BlocSelector<AndroidSifredZenleKaydetBloc, AndroidSifredZenleKaydetState, TextEditingController?>(selector: (state) => state.newPasswordController, builder: (context, newPasswordController) {return CustomTextFormField(controller: newPasswordController, hintText: "lbl_yeni_ifre".tr);})); } 
/// Section Widget
Widget _buildConfirmNewPassword(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 23.h), child: BlocSelector<AndroidSifredZenleKaydetBloc, AndroidSifredZenleKaydetState, TextEditingController?>(selector: (state) => state.confirmNewPasswordController, builder: (context, confirmNewPasswordController) {return CustomTextFormField(controller: confirmNewPasswordController, hintText: "msg_yeni_ifre_tekrar".tr, textInputAction: TextInputAction.done, alignment: Alignment.centerRight);})); } 
/// Section Widget
Widget _buildSifremiUnuttum(BuildContext context) { return CustomElevatedButton(width: 140.h, text: "lbl_ifremi_unuttum".tr, buttonStyle: CustomButtonStyles.none, decoration: CustomButtonStyles.gradientPrimaryToTealDecoration, onPressed: () {onTapSifremiUnuttum(context);}); } 
/// Section Widget
Widget _buildKaydet(BuildContext context) { return CustomElevatedButton(width: 100.h, text: "lbl_kaydet".tr, buttonStyle: CustomButtonStyles.none, decoration: CustomButtonStyles.gradientPrimaryToTealDecoration); } 
/// Navigates to the ayarlarSayfasBildirimlerAKOneScreen when the action is triggered.
onTapSend(BuildContext context) { NavigatorService.pushNamed(AppRoutes.ayarlarSayfasBildirimlerAKOneScreen, ); } 
/// Navigates to the homeTwoScreen when the action is triggered.
onTapLogo(BuildContext context) { NavigatorService.pushNamed(AppRoutes.homeTwoScreen, ); } 
/// Navigates to the androidSifremiunuttumScreen when the action is triggered.
onTapSifremiUnuttum(BuildContext context) { NavigatorService.pushNamed(AppRoutes.androidSifremiunuttumScreen, ); } 
/// Navigates to the homeScreen when the action is triggered.
onTapImgSuccess(BuildContext context) { NavigatorService.pushNamed(AppRoutes.homeScreen, ); } 
 }
