import 'bloc/giri_bloc.dart';import 'models/giri_model.dart';import 'package:flutter/material.dart';import 'package:smart_watch_control/core/app_export.dart';import 'package:smart_watch_control/widgets/custom_elevated_button.dart';class GiriScreen extends StatelessWidget {const GiriScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<GiriBloc>(create: (context) => GiriBloc(GiriState(giriModelObj: GiriModel()))..add(GiriInitialEvent()), child: GiriScreen()); } 
@override Widget build(BuildContext context) { return BlocBuilder<GiriBloc, GiriState>(builder: (context, state) {return SafeArea(child: Scaffold(body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 59.v), child: Column(children: [CustomImageView(imagePath: ImageConstant.imgLogo, height: 100.v, width: 117.h, radius: BorderRadius.circular(50.h)), SizedBox(height: 34.v), Text("lbl_msl".tr, style: theme.textTheme.displayLarge), SizedBox(height: 35.v), Text("lbl_my_safing_life".tr, style: CustomTextStyles.titleLargeBluegray800), SizedBox(height: 58.v), Padding(padding: EdgeInsets.only(left: 1.h), child: Column(children: [CustomElevatedButton(width: 175.h, text: "lbl_kay_t_ol".tr, buttonStyle: CustomButtonStyles.none, decoration: CustomButtonStyles.gradientPrimaryToTealDecoration, onPressed: () {onTapKaytOl(context);}), SizedBox(height: 35.v), CustomElevatedButton(width: 175.h, text: "lbl_giri".tr, buttonStyle: CustomButtonStyles.none, decoration: CustomButtonStyles.gradientPrimaryToTealDecoration, onPressed: () {onTapGiri(context);})])), SizedBox(height: 5.v)]))));}); } 
/// Navigates to the androidKayitformScreen when the action is triggered.
onTapKaytOl(BuildContext context) { NavigatorService.pushNamed(AppRoutes.androidKayitformScreen, ); } 
/// Navigates to the androidGirisformScreen when the action is triggered.
onTapGiri(BuildContext context) { NavigatorService.pushNamed(AppRoutes.androidGirisformScreen, ); } 
 }
