import 'bloc/android_kayitform_bloc.dart';import 'models/android_kayitform_model.dart';import 'package:flutter/material.dart';import 'package:smart_watch_control/core/app_export.dart';import 'package:smart_watch_control/core/utils/validation_functions.dart';import 'package:smart_watch_control/widgets/custom_elevated_button.dart';import 'package:smart_watch_control/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable
class AndroidKayitformScreen extends StatelessWidget {AndroidKayitformScreen({Key? key}) : super(key: key);

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

static Widget builder(BuildContext context) { return BlocProvider<AndroidKayitformBloc>(create: (context) => AndroidKayitformBloc(AndroidKayitformState(androidKayitformModelObj: AndroidKayitformModel()))..add(AndroidKayitformInitialEvent()), child: AndroidKayitformScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: Form(key: _formKey, child: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 4.v), child: Column(children: [_buildSendRow(context), SizedBox(height: 12.v), _buildPhoneNumberEditText(context), SizedBox(height: 20.v), _buildEmailEditText(context), SizedBox(height: 16.v), _buildUsernameEditText(context), SizedBox(height: 21.v), _buildPasswordEditText(context), SizedBox(height: 26.v), _buildConfirmPasswordEditText(context), SizedBox(height: 34.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 26.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Container(height: 40.v, width: 35.h, margin: EdgeInsets.only(top: 5.v), child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgAkarIconsArrowRight, height: 20.adaptSize, width: 20.adaptSize, alignment: Alignment.topLeft, margin: EdgeInsets.only(top: 4.v)), CustomImageView(imagePath: ImageConstant.imgIconBasket, height: 40.v, width: 34.h, alignment: Alignment.center)])), Container(width: 147.h, margin: EdgeInsets.only(left: 45.h, bottom: 3.v), child: Text("msg_kullan_c_s_zle_mesini".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.bodyMediumDMSansPrimaryContainer))]))), SizedBox(height: 6.v)]))), bottomNavigationBar: _buildKayitOlButton(context))); } 
/// Section Widget
Widget _buildSendRow(BuildContext context) { return Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(right: 28.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgSend, height: 39.adaptSize, width: 39.adaptSize, margin: EdgeInsets.only(bottom: 30.v), onTap: () {onTapImgSend(context);}), Spacer(flex: 65), Padding(padding: EdgeInsets.only(top: 22.v), child: Text("lbl_kay_t_ol".tr, style: theme.textTheme.displaySmall)), Spacer(flex: 34), CustomImageView(imagePath: ImageConstant.imgLogo30x35, height: 30.v, width: 35.h, radius: BorderRadius.circular(15.h), margin: EdgeInsets.only(top: 12.v, bottom: 27.v), onTap: () {onTapImgLogo(context);})]))); } 
/// Section Widget
Widget _buildPhoneNumberEditText(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 26.h, right: 29.h), child: BlocSelector<AndroidKayitformBloc, AndroidKayitformState, TextEditingController?>(selector: (state) => state.phoneNumberEditTextController, builder: (context, phoneNumberEditTextController) {return CustomTextFormField(controller: phoneNumberEditTextController, hintText: "msg_telelefon_numaras".tr, contentPadding: EdgeInsets.symmetric(horizontal: 10.h, vertical: 15.v));})); } 
/// Section Widget
Widget _buildEmailEditText(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 26.h, right: 29.h), child: BlocSelector<AndroidKayitformBloc, AndroidKayitformState, TextEditingController?>(selector: (state) => state.emailEditTextController, builder: (context, emailEditTextController) {return CustomTextFormField(controller: emailEditTextController, hintText: "lbl_email".tr, textInputType: TextInputType.emailAddress, validator: (value) {if (value == null || (!isValidEmail(value, isRequired: true))) {return "err_msg_please_enter_valid_email".tr;} return null;}, contentPadding: EdgeInsets.symmetric(horizontal: 14.h, vertical: 15.v));})); } 
/// Section Widget
Widget _buildUsernameEditText(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 26.h, right: 29.h), child: BlocSelector<AndroidKayitformBloc, AndroidKayitformState, TextEditingController?>(selector: (state) => state.usernameEditTextController, builder: (context, usernameEditTextController) {return CustomTextFormField(controller: usernameEditTextController, hintText: "lbl_kullan_c_ad".tr, contentPadding: EdgeInsets.symmetric(horizontal: 14.h, vertical: 15.v));})); } 
/// Section Widget
Widget _buildPasswordEditText(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 26.h, right: 28.h), child: BlocSelector<AndroidKayitformBloc, AndroidKayitformState, TextEditingController?>(selector: (state) => state.passwordEditTextController, builder: (context, passwordEditTextController) {return CustomTextFormField(controller: passwordEditTextController, hintText: "lbl_ifre".tr, contentPadding: EdgeInsets.symmetric(horizontal: 14.h, vertical: 15.v));})); } 
/// Section Widget
Widget _buildConfirmPasswordEditText(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 26.h, right: 29.h), child: BlocSelector<AndroidKayitformBloc, AndroidKayitformState, TextEditingController?>(selector: (state) => state.confirmPasswordEditTextController, builder: (context, confirmPasswordEditTextController) {return CustomTextFormField(controller: confirmPasswordEditTextController, hintText: "lbl_ifre_tekrar".tr, textInputAction: TextInputAction.done, contentPadding: EdgeInsets.symmetric(horizontal: 8.h, vertical: 15.v));})); } 
/// Section Widget
Widget _buildKayitOlButton(BuildContext context) { return CustomElevatedButton(width: 175.h, text: "lbl_kay_t_ol".tr, margin: EdgeInsets.only(left: 93.h, right: 92.h, bottom: 51.v), buttonStyle: CustomButtonStyles.none, decoration: CustomButtonStyles.gradientPrimaryToTealDecoration, onPressed: () {onTapKayitOlButton(context);}); } 
/// Navigates to the giriScreen when the action is triggered.
onTapImgSend(BuildContext context) { NavigatorService.pushNamed(AppRoutes.giriScreen, ); } 
/// Navigates to the giriScreen when the action is triggered.
onTapImgLogo(BuildContext context) { NavigatorService.pushNamed(AppRoutes.giriScreen, ); } 
/// Navigates to the androidGirisformScreen when the action is triggered.
onTapKayitOlButton(BuildContext context) { NavigatorService.pushNamed(AppRoutes.androidGirisformScreen, ); } 
 }
