import 'bloc/android_girisform_bloc.dart';import 'models/android_girisform_model.dart';import 'package:flutter/material.dart';import 'package:smart_watch_control/core/app_export.dart';import 'package:smart_watch_control/widgets/custom_elevated_button.dart';import 'package:smart_watch_control/widgets/custom_text_form_field.dart';class AndroidGirisformScreen extends StatelessWidget {const AndroidGirisformScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<AndroidGirisformBloc>(create: (context) => AndroidGirisformBloc(AndroidGirisformState(androidGirisformModelObj: AndroidGirisformModel()))..add(AndroidGirisformInitialEvent()), child: AndroidGirisformScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 10.h, vertical: 11.v), child: Column(children: [Align(alignment: Alignment.centerLeft, child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgSend, height: 39.v, width: 42.h, margin: EdgeInsets.only(bottom: 94.v), onTap: () {onTapImgSend(context);}), CustomImageView(imagePath: ImageConstant.imgLogo, height: 100.v, width: 117.h, radius: BorderRadius.circular(50.h), margin: EdgeInsets.only(left: 64.h, top: 33.v), onTap: () {onTapImgLogo(context);})])), SizedBox(height: 48.v), Text("lbl_giri".tr, style: theme.textTheme.displaySmall), SizedBox(height: 34.v), Padding(padding: EdgeInsets.only(left: 21.h, right: 14.h), child: BlocSelector<AndroidGirisformBloc, AndroidGirisformState, TextEditingController?>(selector: (state) => state.usernameController, builder: (context, usernameController) {return CustomTextFormField(controller: usernameController, hintText: "lbl_kullan_c_ad".tr, textInputAction: TextInputAction.done, contentPadding: EdgeInsets.symmetric(horizontal: 30.h, vertical: 15.v), borderDecoration: TextFormFieldStyleHelper.fillWhiteA);})), SizedBox(height: 34.v), CustomElevatedButton(height: 58.v, text: "lbl_ifre".tr, margin: EdgeInsets.only(left: 21.h, right: 14.h), buttonStyle: CustomButtonStyles.fillWhiteA, buttonTextStyle: theme.textTheme.titleLarge!), SizedBox(height: 29.v), Align(alignment: Alignment.centerRight, child: Padding(padding: EdgeInsets.only(right: 118.h), child: Row(mainAxisAlignment: MainAxisAlignment.end, crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_giri".tr, style: CustomTextStyles.titleLargeWhiteA700), CustomImageView(imagePath: ImageConstant.imgAkarIconsArrowRight, height: 20.adaptSize, width: 20.adaptSize, margin: EdgeInsets.only(left: 11.h, bottom: 5.v))]))), SizedBox(height: 9.v), CustomElevatedButton(width: 175.h, text: "lbl_giri".tr, buttonStyle: CustomButtonStyles.none, decoration: CustomButtonStyles.gradientPrimaryToTealDecoration, onPressed: () {onTapGiri(context);}), SizedBox(height: 15.v), SizedBox(height: 45.v, width: 113.h, child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.topCenter, child: Text("lbl_login".tr, style: CustomTextStyles.titleLargeWhiteA700)), Align(alignment: Alignment.bottomCenter, child: GestureDetector(onTap: () {onTapTxtIfremiUnuttum(context);}, child: Text("lbl_ifremi_unuttum".tr, style: CustomTextStyles.bodyMediumDMSansGray800)))])), SizedBox(height: 5.v)])))); } 
/// Navigates to the giriScreen when the action is triggered.
onTapImgSend(BuildContext context) { NavigatorService.pushNamed(AppRoutes.giriScreen, ); } 
/// Navigates to the giriScreen when the action is triggered.
onTapImgLogo(BuildContext context) { NavigatorService.pushNamed(AppRoutes.giriScreen, ); } 
/// Navigates to the homeScreen when the action is triggered.
onTapGiri(BuildContext context) { NavigatorService.pushNamed(AppRoutes.homeScreen, ); } 
/// Navigates to the androidSifremiunuttumScreen when the action is triggered.
onTapTxtIfremiUnuttum(BuildContext context) { NavigatorService.pushNamed(AppRoutes.androidSifremiunuttumScreen, ); } 
 }
