import 'bloc/android_teld_zenle_bloc.dart';import 'models/android_teld_zenle_model.dart';import 'package:flutter/material.dart';import 'package:smart_watch_control/core/app_export.dart';import 'package:smart_watch_control/widgets/app_bar/appbar_leading_image.dart';import 'package:smart_watch_control/widgets/app_bar/appbar_trailing_circleimage.dart';import 'package:smart_watch_control/widgets/app_bar/custom_app_bar.dart';import 'package:smart_watch_control/widgets/custom_elevated_button.dart';import 'package:smart_watch_control/widgets/custom_text_form_field.dart';class AndroidTeldZenleScreen extends StatelessWidget {const AndroidTeldZenleScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<AndroidTeldZenleBloc>(create: (context) => AndroidTeldZenleBloc(AndroidTeldZenleState(androidTeldZenleModelObj: AndroidTeldZenleModel()))..add(AndroidTeldZenleInitialEvent()), child: AndroidTeldZenleScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 5.v), child: Column(children: [CustomImageView(imagePath: ImageConstant.imgLogo90x106, height: 90.v, width: 106.h, radius: BorderRadius.circular(45.h)), SizedBox(height: 62.v), Text("msg_telefon_numaras".tr, style: theme.textTheme.headlineLarge), SizedBox(height: 62.v), Padding(padding: EdgeInsets.only(left: 23.h), child: BlocSelector<AndroidTeldZenleBloc, AndroidTeldZenleState, TextEditingController?>(selector: (state) => state.phoneNumberController, builder: (context, phoneNumberController) {return CustomTextFormField(controller: phoneNumberController, hintText: "lbl_505_573_48_26".tr, textInputAction: TextInputAction.done, alignment: Alignment.centerRight);})), SizedBox(height: 52.v), CustomElevatedButton(width: 100.h, text: "lbl_kaydet".tr, buttonStyle: CustomButtonStyles.none, decoration: CustomButtonStyles.gradientPrimaryToTealDecoration, onPressed: () {onTapKaydet(context);}), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 49.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgSend, margin: EdgeInsets.only(left: 7.h, top: 5.v, bottom: 5.v), onTap: () {onTapSend(context);}), actions: [AppbarTrailingCircleimage(imagePath: ImageConstant.imgLogo30x35, margin: EdgeInsets.fromLTRB(21.h, 10.v, 21.h, 9.v), onTap: () {onTapLogo(context);})]); } 
/// Navigates to the ayarlarSayfasBildirimlerAKOneScreen when the action is triggered.
onTapSend(BuildContext context) { NavigatorService.pushNamed(AppRoutes.ayarlarSayfasBildirimlerAKOneScreen, ); } 
/// Navigates to the homeTwoScreen when the action is triggered.
onTapLogo(BuildContext context) { NavigatorService.pushNamed(AppRoutes.homeTwoScreen, ); } 
/// Navigates to the androidTeldZenleKaydetScreen when the action is triggered.
onTapKaydet(BuildContext context) { NavigatorService.pushNamed(AppRoutes.androidTeldZenleKaydetScreen, ); } 
 }
