import '../m_zik_listesi_screen/widgets/musiclistdetail_item_widget.dart';import 'bloc/m_zik_listesi_bloc.dart';import 'models/m_zik_listesi_model.dart';import 'models/musiclistdetail_item_model.dart';import 'package:flutter/material.dart';import 'package:smart_watch_control/core/app_export.dart';class MZikListesiScreen extends StatelessWidget {const MZikListesiScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<MZikListesiBloc>(create: (context) => MZikListesiBloc(MZikListesiState(mZikListesiModelObj: MZikListesiModel()))..add(MZikListesiInitialEvent()), child: MZikListesiScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(body: SizedBox(height: 605.v, width: double.maxFinite, child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.topCenter, child: Container(height: 180.v, width: double.maxFinite, decoration: BoxDecoration(gradient: LinearGradient(begin: Alignment(0.5, 0), end: Alignment(0.5, 1), colors: [theme.colorScheme.errorContainer, appTheme.indigo300.withOpacity(0)])))), Align(alignment: Alignment.bottomCenter, child: Container(margin: EdgeInsets.only(left: 27.h, right: 27.h, bottom: 2.v), padding: EdgeInsets.symmetric(horizontal: 27.h, vertical: 7.v), decoration: BoxDecoration(borderRadius: BorderRadiusStyle.roundedBorder40), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 65.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgGroup19, height: 23.adaptSize, width: 23.adaptSize), Padding(padding: EdgeInsets.only(left: 6.h, top: 3.v, bottom: 4.v), child: Text("lbl_m_zik_ekle".tr, style: CustomTextStyles.bodySmallBlack900))])), SizedBox(height: 11.v), _buildMusicListDetail(context), SizedBox(height: 11.v)])))])))); } 
/// Section Widget
Widget _buildMusicListDetail(BuildContext context) { return BlocSelector<MZikListesiBloc, MZikListesiState, MZikListesiModel?>(selector: (state) => state.mZikListesiModelObj, builder: (context, mZikListesiModelObj) {return ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 8.v);}, itemCount: mZikListesiModelObj?.musiclistdetailItemList.length ?? 0, itemBuilder: (context, index) {MusiclistdetailItemModel model = mZikListesiModelObj?.musiclistdetailItemList[index] ?? MusiclistdetailItemModel(); return MusiclistdetailItemWidget(model, onTapImgImage: () {onTapImgImage(context);});});}); } 
/// Navigates to the mZikListesiSilindiBaArLScreen when the action is triggered.
onTapImgImage(BuildContext context) { NavigatorService.pushNamed(AppRoutes.mZikListesiSilindiBaArLScreen, ); } 
 }
