import '../m_zik_listesi_silindi_ba_ar_l_screen/widgets/musiclist_item_widget.dart';import 'bloc/m_zik_listesi_silindi_ba_ar_l_bloc.dart';import 'models/m_zik_listesi_silindi_ba_ar_l_model.dart';import 'models/musiclist_item_model.dart';import 'package:flutter/material.dart';import 'package:smart_watch_control/core/app_export.dart';import 'package:smart_watch_control/widgets/app_bar/appbar_leading_image.dart';import 'package:smart_watch_control/widgets/app_bar/appbar_trailing_circleimage.dart';import 'package:smart_watch_control/widgets/app_bar/custom_app_bar.dart';class MZikListesiSilindiBaArLScreen extends StatelessWidget {const MZikListesiSilindiBaArLScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<MZikListesiSilindiBaArLBloc>(create: (context) => MZikListesiSilindiBaArLBloc(MZikListesiSilindiBaArLState(mZikListesiSilindiBaArLModelObj: MZikListesiSilindiBaArLModel()))..add(MZikListesiSilindiBaArLInitialEvent()), child: MZikListesiSilindiBaArLScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: 306.h, margin: EdgeInsets.only(left: 24.h, right: 30.h, bottom: 5.v), padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 19.v), decoration: BoxDecoration(borderRadius: BorderRadiusStyle.roundedBorder40), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 71.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgGroup19, height: 23.adaptSize, width: 23.adaptSize), Padding(padding: EdgeInsets.only(left: 6.h, top: 3.v, bottom: 4.v), child: Text("lbl_m_zik_ekle".tr, style: CustomTextStyles.bodySmallBlack900))])), SizedBox(height: 14.v), _buildMusicList(context), SizedBox(height: 63.v), CustomImageView(imagePath: ImageConstant.imgSuccess, height: 25.v, width: 80.h, margin: EdgeInsets.only(left: 82.h), onTap: () {onTapImgSuccess(context);}), SizedBox(height: 38.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 215.v, leadingWidth: 54.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgSend, margin: EdgeInsets.only(left: 32.h, top: 17.v, bottom: 179.v), onTap: () {onTapSend(context);}), actions: [AppbarTrailingCircleimage(imagePath: ImageConstant.imgLogo30x35, margin: EdgeInsets.fromLTRB(19.h, 11.v, 19.h, 174.v), onTap: () {onTapLogo(context);})], styleType: Style.bgGradientnameerrorContainernameindigo300opacity0); } 
/// Section Widget
Widget _buildMusicList(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 6.h), child: BlocSelector<MZikListesiSilindiBaArLBloc, MZikListesiSilindiBaArLState, MZikListesiSilindiBaArLModel?>(selector: (state) => state.mZikListesiSilindiBaArLModelObj, builder: (context, mZikListesiSilindiBaArLModelObj) {return ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 8.v);}, itemCount: mZikListesiSilindiBaArLModelObj?.musiclistItemList.length ?? 0, itemBuilder: (context, index) {MusiclistItemModel model = mZikListesiSilindiBaArLModelObj?.musiclistItemList[index] ?? MusiclistItemModel(); return MusiclistItemWidget(model);});})); } 
/// Navigates to the homeTwoScreen when the action is triggered.
onTapSend(BuildContext context) { NavigatorService.pushNamed(AppRoutes.homeTwoScreen, ); } 
/// Navigates to the homeScreen when the action is triggered.
onTapLogo(BuildContext context) { NavigatorService.pushNamed(AppRoutes.homeScreen, ); } 
/// Navigates to the homeScreen when the action is triggered.
onTapImgSuccess(BuildContext context) { NavigatorService.pushNamed(AppRoutes.homeScreen, ); } 
 }
