import 'bloc/android_eposta_d_zenle_bloc.dart';import 'models/android_eposta_d_zenle_model.dart';import 'package:flutter/material.dart';import 'package:smart_watch_control/core/app_export.dart';import 'package:smart_watch_control/core/utils/validation_functions.dart';import 'package:smart_watch_control/widgets/app_bar/appbar_leading_image.dart';import 'package:smart_watch_control/widgets/app_bar/appbar_trailing_circleimage.dart';import 'package:smart_watch_control/widgets/app_bar/custom_app_bar.dart';import 'package:smart_watch_control/widgets/custom_elevated_button.dart';import 'package:smart_watch_control/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable
class AndroidEpostaDZenleScreen extends StatelessWidget {AndroidEpostaDZenleScreen({Key? key}) : super(key: key);

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

static Widget builder(BuildContext context) { return BlocProvider<AndroidEpostaDZenleBloc>(create: (context) => AndroidEpostaDZenleBloc(AndroidEpostaDZenleState(androidEpostaDZenleModelObj: AndroidEpostaDZenleModel()))..add(AndroidEpostaDZenleInitialEvent()), child: AndroidEpostaDZenleScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Form(key: _formKey, child: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 27.h, vertical: 3.v), child: Column(children: [CustomImageView(imagePath: ImageConstant.imgLogo90x106, height: 90.v, width: 106.h, radius: BorderRadius.circular(45.h), alignment: Alignment.centerRight, margin: EdgeInsets.only(right: 88.h)), SizedBox(height: 41.v), Text("lbl_e_posta_yenile".tr, style: theme.textTheme.headlineLarge), SizedBox(height: 49.v), BlocSelector<AndroidEpostaDZenleBloc, AndroidEpostaDZenleState, TextEditingController?>(selector: (state) => state.emailController, builder: (context, emailController) {return CustomTextFormField(controller: emailController, hintText: "msg_ayse45_gmail_com".tr, textInputAction: TextInputAction.done, textInputType: TextInputType.emailAddress, validator: (value) {if (value == null || (!isValidEmail(value, isRequired: true))) {return "err_msg_please_enter_valid_email".tr;} return null;});}), SizedBox(height: 80.v), CustomElevatedButton(text: "msg_do_rulama_kodu_g_nder".tr, margin: EdgeInsets.only(left: 41.h, right: 40.h), buttonStyle: CustomButtonStyles.none, decoration: CustomButtonStyles.gradientPrimaryToTealDecoration, onPressed: () {onTapDorulamaKoduGnder(context);}), SizedBox(height: 5.v)]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 49.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgSend, margin: EdgeInsets.only(left: 7.h, top: 5.v, bottom: 5.v), onTap: () {onTapSend(context);}), actions: [AppbarTrailingCircleimage(imagePath: ImageConstant.imgLogo30x35, margin: EdgeInsets.fromLTRB(22.h, 10.v, 22.h, 9.v), onTap: () {onTapLogo(context);})]); } 
/// Navigates to the ayarlarSayfasBildirimlerAKOneScreen when the action is triggered.
onTapSend(BuildContext context) { NavigatorService.pushNamed(AppRoutes.ayarlarSayfasBildirimlerAKOneScreen, ); } 
/// Navigates to the homeTwoScreen when the action is triggered.
onTapLogo(BuildContext context) { NavigatorService.pushNamed(AppRoutes.homeTwoScreen, ); } 
/// Navigates to the androidEpostaDZenleKaydetScreen when the action is triggered.
onTapDorulamaKoduGnder(BuildContext context) { NavigatorService.pushNamed(AppRoutes.androidEpostaDZenleKaydetScreen, ); } 
 }
