import 'bloc/g_venli_alan_sayfas_bloc.dart';import 'models/g_venli_alan_sayfas_model.dart';import 'package:flutter/material.dart';import 'package:smart_watch_control/core/app_export.dart';import 'package:smart_watch_control/widgets/app_bar/appbar_leading_image.dart';import 'package:smart_watch_control/widgets/app_bar/appbar_subtitle_three.dart';import 'package:smart_watch_control/widgets/app_bar/appbar_trailing_circleimage.dart';import 'package:smart_watch_control/widgets/app_bar/custom_app_bar.dart';class GVenliAlanSayfasPage extends StatelessWidget {const GVenliAlanSayfasPage({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<GVenliAlanSayfasBloc>(create: (context) => GVenliAlanSayfasBloc(GVenliAlanSayfasState(gVenliAlanSayfasModelObj: GVenliAlanSayfasModel()))..add(GVenliAlanSayfasInitialEvent()), child: GVenliAlanSayfasPage()); } 
@override Widget build(BuildContext context) { return BlocBuilder<GVenliAlanSayfasBloc, GVenliAlanSayfasState>(builder: (context, state) {return SafeArea(child: Scaffold(body: Container(width: double.maxFinite, decoration: AppDecoration.fillWhiteA, child: Column(children: [_buildFifty(context), Container(margin: EdgeInsets.only(left: 14.h, right: 23.h), padding: EdgeInsets.symmetric(horizontal: 10.h, vertical: 9.v), decoration: BoxDecoration(borderRadius: BorderRadiusStyle.roundedBorder40), child: Column(children: [CustomImageView(imagePath: ImageConstant.imgLogo90x106, height: 90.v, width: 106.h, radius: BorderRadius.circular(45.h)), SizedBox(height: 40.v), _buildMslButton1(context), SizedBox(height: 26.v), _buildMslButton2(context), SizedBox(height: 40.v), _buildMslButton2(context), SizedBox(height: 40.v), _buildMslButton4(context), SizedBox(height: 43.v), Padding(padding: EdgeInsets.only(left: 26.h, right: 31.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [GestureDetector(onTap: () {onTapGNcelKonum(context);}, child: Container(margin: EdgeInsets.only(bottom: 1.v), padding: EdgeInsets.all(8.h), decoration: AppDecoration.gradientPrimaryToTeal.copyWith(borderRadius: BorderRadiusStyle.circleBorder20), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgPhoneIcon, height: 24.adaptSize, width: 24.adaptSize), Padding(padding: EdgeInsets.only(left: 6.h, top: 4.v, bottom: 4.v), child: Text("lbl_g_ncel_konum".tr, style: CustomTextStyles.labelLargeWhiteA700))]))), CustomImageView(imagePath: ImageConstant.imgIconPlus, height: 40.adaptSize, width: 40.adaptSize)])), SizedBox(height: 5.v)]))]))));}); } 
/// Section Widget
Widget _buildFifty(BuildContext context) { return Container(decoration: AppDecoration.gradientTealToWhiteA, child: CustomAppBar(height: 46.v, leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgSend, margin: EdgeInsets.only(left: 6.h, top: 6.v, bottom: 1.v), onTap: () {onTapSend(context);}), centerTitle: true, title: AppbarSubtitleThree(text: "lbl_g_venl_alanlar".tr), actions: [AppbarTrailingCircleimage(imagePath: ImageConstant.imgLogo30x35, margin: EdgeInsets.fromLTRB(16.h, 11.v, 16.h, 5.v), onTap: () {onTapLogo(context);})], styleType: Style.bgFill)); } 
/// Section Widget
Widget _buildMslButton1(BuildContext context) { return SizedBox(height: 40.v, width: 300.h, child: Stack(alignment: Alignment.topLeft, children: [Align(alignment: Alignment.center, child: GestureDetector(onTap: () {onTapVector(context);}, child: Container(decoration: AppDecoration.gradientPrimaryToTeal.copyWith(borderRadius: BorderRadiusStyle.circleBorder20), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 4.v), Opacity(opacity: 0.15, child: CustomImageView(imagePath: ImageConstant.imgVectorWhiteA700, height: 35.v, width: 300.h))])))), Align(alignment: Alignment.topLeft, child: Padding(padding: EdgeInsets.fromLTRB(15.h, 7.v, 25.h, 7.v), child: Row(crossAxisAlignment: CrossAxisAlignment.end, children: [CustomImageView(imagePath: ImageConstant.imgHome, height: 24.adaptSize, width: 24.adaptSize), Padding(padding: EdgeInsets.only(left: 9.h, top: 2.v), child: Text("lbl_ev".tr, style: theme.textTheme.titleMedium)), Spacer(), CustomImageView(imagePath: ImageConstant.imgArrowRightGray50, height: 13.v, width: 8.h, margin: EdgeInsets.only(top: 6.v, bottom: 4.v))])))])); } 
/// Section Widget
Widget _buildMslButton4(BuildContext context) { return SizedBox(height: 40.v, width: 300.h, child: Stack(alignment: Alignment.centerLeft, children: [Align(alignment: Alignment.center, child: GestureDetector(onTap: () {onTapVector3(context);}, child: Container(decoration: AppDecoration.gradientPrimaryToTeal.copyWith(borderRadius: BorderRadiusStyle.circleBorder20), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 4.v), Opacity(opacity: 0.15, child: CustomImageView(imagePath: ImageConstant.imgVectorWhiteA700, height: 35.v, width: 300.h))])))), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.fromLTRB(11.h, 8.v, 25.h, 8.v), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgLaSchool, height: 24.adaptSize, width: 24.adaptSize), Padding(padding: EdgeInsets.only(left: 13.h), child: Text("lbl_kurs".tr, style: theme.textTheme.titleMedium)), Spacer(), CustomImageView(imagePath: ImageConstant.imgArrowRightGray50, height: 13.v, width: 8.h, margin: EdgeInsets.symmetric(vertical: 5.v))])))])); } 
/// Common widget
Widget _buildMslButton2(BuildContext context, {Function? onTapVector, }) { return SizedBox(height: 40.v, width: 300.h, child: Stack(alignment: Alignment.centerLeft, children: [GestureDetector(onTap: () {onTapVector!.call();}, child: Align(alignment: Alignment.center, child: Container(decoration: AppDecoration.gradientPrimaryToTeal.copyWith(borderRadius: BorderRadiusStyle.circleBorder20), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 4.v), Opacity(opacity: 0.15, child: CustomImageView(imagePath: ImageConstant.imgVectorWhiteA700, height: 35.v, width: 300.h))])))), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.fromLTRB(14.h, 8.v, 25.h, 8.v), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgLaSchool, height: 24.adaptSize, width: 24.adaptSize), Padding(padding: EdgeInsets.only(left: 10.h), child: Text("lbl_okul".tr, style: theme.textTheme.titleMedium)), Spacer(), CustomImageView(imagePath: ImageConstant.imgArrowRightGray50, height: 13.v, width: 8.h, margin: EdgeInsets.symmetric(vertical: 5.v))])))])); } 
/// Navigates to the homeTwoScreen when the action is triggered.
onTapSend(BuildContext context) { NavigatorService.pushNamed(AppRoutes.homeTwoScreen, ); } 
/// Navigates to the homeScreen when the action is triggered.
onTapLogo(BuildContext context) { NavigatorService.pushNamed(AppRoutes.homeScreen, ); } 
/// Navigates to the gVenliAlanDetayScreen when the action is triggered.
onTapVector(BuildContext context) { NavigatorService.pushNamed(AppRoutes.gVenliAlanDetayScreen, ); } 
/// Navigates to the gVenliAlanDetayScreen when the action is triggered.
onTapVector1(BuildContext context) { NavigatorService.pushNamed(AppRoutes.gVenliAlanDetayScreen, ); } 
/// Navigates to the gVenliAlanDetayScreen when the action is triggered.
onTapVector2(BuildContext context) { NavigatorService.pushNamed(AppRoutes.gVenliAlanDetayScreen, ); } 
/// Navigates to the gVenliAlanDetayScreen when the action is triggered.
onTapVector3(BuildContext context) { NavigatorService.pushNamed(AppRoutes.gVenliAlanDetayScreen, ); } 
/// Navigates to the gNcelKonumScreen when the action is triggered.
onTapGNcelKonum(BuildContext context) { NavigatorService.pushNamed(AppRoutes.gNcelKonumScreen, ); } 
 }
