import 'bloc/kisilerd_zenle_one_bloc.dart';import 'models/kisilerd_zenle_one_model.dart';import 'package:flutter/material.dart';import 'package:smart_watch_control/core/app_export.dart';import 'package:smart_watch_control/widgets/app_bar/appbar_leading_image.dart';import 'package:smart_watch_control/widgets/app_bar/appbar_title.dart';import 'package:smart_watch_control/widgets/app_bar/appbar_trailing_circleimage.dart';import 'package:smart_watch_control/widgets/app_bar/custom_app_bar.dart';import 'package:smart_watch_control/widgets/custom_elevated_button.dart';class KisilerdZenleOneScreen extends StatelessWidget {const KisilerdZenleOneScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<KisilerdZenleOneBloc>(create: (context) => KisilerdZenleOneBloc(KisilerdZenleOneState(kisilerdZenleOneModelObj: KisilerdZenleOneModel()))..add(KisilerdZenleOneInitialEvent()), child: KisilerdZenleOneScreen()); } 
@override Widget build(BuildContext context) { return BlocBuilder<KisilerdZenleOneBloc, KisilerdZenleOneState>(builder: (context, state) {return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 513.v, width: double.maxFinite, child: Stack(alignment: Alignment.topCenter, children: [Align(alignment: Alignment.bottomCenter, child: Container(height: 385.v, width: 250.h, padding: EdgeInsets.symmetric(horizontal: 26.h, vertical: 15.v), decoration: AppDecoration.gradientTealDToBlue.copyWith(borderRadius: BorderRadiusStyle.circleBorder50), child: CustomImageView(imagePath: ImageConstant.imgClarityEditLine, height: 24.adaptSize, width: 24.adaptSize, alignment: Alignment.topRight))), _buildAppBar(context), CustomImageView(imagePath: ImageConstant.imgUnsplash6dmx8ynkpgo154x158, height: 154.v, width: 158.h, radius: BorderRadius.circular(79.h), alignment: Alignment.topCenter, margin: EdgeInsets.only(top: 166.v)), Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.only(left: 87.h, right: 87.h, bottom: 93.v), child: Column(mainAxisSize: MainAxisSize.min, children: [CustomElevatedButton(height: 25.v, text: "lbl_annem".tr, buttonStyle: CustomButtonStyles.fillOnPrimaryContainer, buttonTextStyle: theme.textTheme.bodyMedium!), SizedBox(height: 25.v), Container(width: 185.h, padding: EdgeInsets.symmetric(horizontal: 30.h, vertical: 3.v), decoration: AppDecoration.fillOnPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Text("msg_972_52_670_610".tr, style: theme.textTheme.bodyMedium))])))])), _buildDeleteButtons(context)]))));}); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 215.v, leadingWidth: 33.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgPrevious1, margin: EdgeInsets.only(left: 11.h, top: 14.v, bottom: 182.v), onTap: () {onTapPreviousOne(context);}), centerTitle: true, title: AppbarTitle(text: "lbl_ki_i_d_zenle".tr, margin: EdgeInsets.only(top: 20.v, bottom: 169.v)), actions: [AppbarTrailingCircleimage(imagePath: ImageConstant.imgLogo30x35, margin: EdgeInsets.fromLTRB(19.h, 14.v, 19.h, 171.v), onTap: () {onTapLogo(context);})], styleType: Style.bgGradientnameerrorContainernameindigo300opacity0_1); } 
/// Section Widget
Widget _buildDeleteButtons(BuildContext context) { return Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 14.v), child: Row(mainAxisAlignment: MainAxisAlignment.spaceEvenly, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomElevatedButton(height: 36.v, width: 94.h, text: "lbl_sil".tr, margin: EdgeInsets.only(bottom: 63.v), buttonStyle: CustomButtonStyles.none, decoration: CustomButtonStyles.gradientPrimaryToTealDecoration, buttonTextStyle: theme.textTheme.bodyMedium!), CustomElevatedButton(height: 36.v, width: 94.h, text: "lbl_kaydet".tr, margin: EdgeInsets.only(bottom: 63.v), buttonStyle: CustomButtonStyles.none, decoration: CustomButtonStyles.gradientPrimaryToTealDecoration, buttonTextStyle: theme.textTheme.bodyMedium!, onPressed: () {onTapKaydet(context);})])); } 
/// Navigates to the gVenliAlanSayfasALRMenScreen when the action is triggered.
onTapPreviousOne(BuildContext context) { NavigatorService.pushNamed(AppRoutes.gVenliAlanSayfasALRMenScreen, ); } 
/// Navigates to the homeScreen when the action is triggered.
onTapLogo(BuildContext context) { NavigatorService.pushNamed(AppRoutes.homeScreen, ); } 
/// Navigates to the kisilerdZenleScreen when the action is triggered.
onTapKaydet(BuildContext context) { NavigatorService.pushNamed(AppRoutes.kisilerdZenleScreen, ); } 
 }
