import '../home_one_screen/widgets/grid2_item_widget.dart';import 'bloc/home_one_bloc.dart';import 'models/grid2_item_model.dart';import 'models/home_one_model.dart';import 'package:flutter/material.dart';import 'package:smart_watch_control/core/app_export.dart';import 'package:smart_watch_control/widgets/custom_elevated_button.dart';import 'package:smart_watch_control/widgets/custom_switch.dart';class HomeOneScreen extends StatelessWidget {const HomeOneScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<HomeOneBloc>(create: (context) => HomeOneBloc(HomeOneState(homeOneModelObj: HomeOneModel()))..add(HomeOneInitialEvent()), child: HomeOneScreen()); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(body: SizedBox(height: 596.v, width: double.maxFinite, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgRectangle152, height: 140.v, width: 360.h, alignment: Alignment.topCenter), Align(alignment: Alignment.center, child: Container(margin: EdgeInsets.symmetric(horizontal: 15.h), padding: EdgeInsets.symmetric(horizontal: 2.h, vertical: 18.v), decoration: BoxDecoration(borderRadius: BorderRadiusStyle.roundedBorder40), child: Column(mainAxisSize: MainAxisSize.min, children: [SizedBox(height: 24.v), Padding(padding: EdgeInsets.only(left: 29.h, right: 17.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.end, children: [CustomImageView(imagePath: ImageConstant.imgUnsplash6dmx8ynkpgo40x48, height: 40.v, width: 48.h, radius: BorderRadius.circular(24.h), margin: EdgeInsets.only(top: 5.v)), Padding(padding: EdgeInsets.only(left: 14.h, top: 16.v, bottom: 13.v), child: Text("lbl_ay_e_gezer".tr, style: CustomTextStyles.labelLargeBlack900)), Spacer(), CustomImageView(imagePath: ImageConstant.imgNabZ, height: 40.adaptSize, width: 40.adaptSize, margin: EdgeInsets.only(bottom: 5.v), onTap: () {onTapImgNabZ(context);})])), SizedBox(height: 28.v), CustomImageView(imagePath: ImageConstant.imgThumbsUp, height: 25.v, width: 13.h), SizedBox(height: 3.v), Padding(padding: EdgeInsets.only(left: 21.h, right: 17.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgRiHotspotLine, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(top: 7.v, bottom: 8.v)), BlocSelector<HomeOneBloc, HomeOneState, bool?>(selector: (state) => state.isSelectedSwitch, builder: (context, isSelectedSwitch) {return CustomSwitch(margin: EdgeInsets.only(left: 10.h, top: 7.v, bottom: 8.v), value: isSelectedSwitch, onChange: (value) {context.read<HomeOneBloc>().add(ChangeSwitchEvent(value: value));});}), Spacer(), SizedBox(height: 40.v, width: 78.h, child: Stack(alignment: Alignment.centerLeft, children: [BlocSelector<HomeOneBloc, HomeOneState, bool?>(selector: (state) => state.isSelectedSwitch1, builder: (context, isSelectedSwitch1) {return CustomSwitch(alignment: Alignment.centerRight, value: isSelectedSwitch1, onChange: (value) {context.read<HomeOneBloc>().add(ChangeSwitch1Event(value: value));});}), CustomImageView(imagePath: ImageConstant.imgAkarIconsLocation, height: 24.adaptSize, width: 24.adaptSize, alignment: Alignment.centerLeft)]))])), SizedBox(height: 38.v), _buildGrid(context), SizedBox(height: 27.v), CustomElevatedButton(width: 140.h, text: "lbl_iki".tr, margin: EdgeInsets.only(right: 80.h), buttonStyle: CustomButtonStyles.none, decoration: CustomButtonStyles.gradientPrimaryToTealDecoration, onPressed: () {onTapIKI(context);}, alignment: Alignment.centerRight)])))])))); } 
/// Section Widget
Widget _buildGrid(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 8.h), child: BlocSelector<HomeOneBloc, HomeOneState, HomeOneModel?>(selector: (state) => state.homeOneModelObj, builder: (context, homeOneModelObj) {return GridView.builder(shrinkWrap: true, gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(mainAxisExtent: 126.v, crossAxisCount: 2, mainAxisSpacing: 17.h, crossAxisSpacing: 17.h), physics: NeverScrollableScrollPhysics(), itemCount: homeOneModelObj?.grid2ItemList.length ?? 0, itemBuilder: (context, index) {Grid2ItemModel model = homeOneModelObj?.grid2ItemList[index] ?? Grid2ItemModel(); return Grid2ItemWidget(model, onTapRehberCard: () {onTapRehberCard(context);});});})); } 
/// Navigates to the mZikListesiScreen when the action is triggered.
onTapRehberCard(BuildContext context) { NavigatorService.pushNamed(AppRoutes.mZikListesiScreen); } 
/// Navigates to the nabZTakipIzelgesiTabContainerScreen when the action is triggered.
onTapImgNabZ(BuildContext context) { NavigatorService.pushNamed(AppRoutes.nabZTakipIzelgesiTabContainerScreen, ); } 
/// Navigates to the giriScreen when the action is triggered.
onTapIKI(BuildContext context) { NavigatorService.pushNamed(AppRoutes.giriScreen, ); } 
 }
