import 'bloc/kisilerd_zenle_bloc.dart';import 'models/kisilerd_zenle_model.dart';import 'package:flutter/material.dart';import 'package:smart_watch_control/core/app_export.dart';import 'package:smart_watch_control/widgets/app_bar/appbar_leading_image.dart';import 'package:smart_watch_control/widgets/app_bar/appbar_title.dart';import 'package:smart_watch_control/widgets/app_bar/appbar_trailing_circleimage.dart';import 'package:smart_watch_control/widgets/app_bar/custom_app_bar.dart';import 'package:smart_watch_control/widgets/custom_elevated_button.dart';import 'package:smart_watch_control/presentation/ki_i_ekle_ba_ar_l_dialog/ki_i_ekle_ba_ar_l_dialog.dart';class KisilerdZenleScreen extends StatelessWidget {const KisilerdZenleScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<KisilerdZenleBloc>(create: (context) => KisilerdZenleBloc(KisilerdZenleState(kisilerdZenleModelObj: KisilerdZenleModel()))..add(KisilerdZenleInitialEvent()), child: KisilerdZenleScreen()); } 
@override Widget build(BuildContext context) { return BlocBuilder<KisilerdZenleBloc, KisilerdZenleState>(builder: (context, state) {return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 513.v, width: double.maxFinite, child: Stack(alignment: Alignment.topCenter, children: [Align(alignment: Alignment.bottomCenter, child: Container(height: 385.v, width: 250.h, padding: EdgeInsets.symmetric(horizontal: 26.h, vertical: 15.v), decoration: AppDecoration.gradientTealDToBlue.copyWith(borderRadius: BorderRadiusStyle.circleBorder50), child: CustomImageView(imagePath: ImageConstant.imgClarityEditLine, height: 24.adaptSize, width: 24.adaptSize, alignment: Alignment.topRight))), _buildAppBar(context), CustomImageView(imagePath: ImageConstant.imgUnsplash6dmx8ynkpgo154x158, height: 154.v, width: 158.h, radius: BorderRadius.circular(79.h), alignment: Alignment.topCenter, margin: EdgeInsets.only(top: 166.v)), Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.only(left: 87.h, right: 87.h, bottom: 93.v), child: Column(mainAxisSize: MainAxisSize.min, children: [CustomElevatedButton(height: 25.v, text: "lbl_annem".tr, buttonStyle: CustomButtonStyles.fillOnPrimaryContainer, buttonTextStyle: theme.textTheme.bodyMedium!), SizedBox(height: 25.v), Container(width: 185.h, padding: EdgeInsets.symmetric(horizontal: 30.h, vertical: 3.v), decoration: AppDecoration.fillOnPrimaryContainer.copyWith(borderRadius: BorderRadiusStyle.roundedBorder12), child: Text("msg_972_52_670_610".tr, style: theme.textTheme.bodyMedium))])))])), _buildSil(context)]))));}); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 215.v, leadingWidth: 33.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgPrevious1, margin: EdgeInsets.only(left: 11.h, top: 14.v, bottom: 182.v), onTap: () {onTapPreviousOne(context);}), centerTitle: true, title: AppbarTitle(text: "lbl_ki_i_d_zenle".tr, margin: EdgeInsets.only(top: 20.v, bottom: 169.v)), actions: [AppbarTrailingCircleimage(imagePath: ImageConstant.imgLogo30x35, margin: EdgeInsets.fromLTRB(19.h, 14.v, 19.h, 171.v), onTap: () {onTapLogo(context);})], styleType: Style.bgGradientnameerrorContainernameindigo300opacity0_1); } 
/// Section Widget
Widget _buildSil(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 55.h, vertical: 14.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(right: 11.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [CustomElevatedButton(height: 36.v, width: 94.h, text: "lbl_sil".tr, buttonStyle: CustomButtonStyles.none, decoration: CustomButtonStyles.gradientPrimaryToTealDecoration, buttonTextStyle: theme.textTheme.bodyMedium!), CustomElevatedButton(height: 36.v, width: 94.h, text: "lbl_kaydet".tr, buttonStyle: CustomButtonStyles.none, decoration: CustomButtonStyles.gradientPrimaryToTealDecoration, buttonTextStyle: theme.textTheme.bodyMedium!, onPressed: () {onTapKaydet(context);})])), SizedBox(height: 14.v), CustomImageView(imagePath: ImageConstant.imgSuccess, height: 25.v, width: 80.h, margin: EdgeInsets.only(left: 75.h), onTap: () {onTapImgSuccess(context);}), SizedBox(height: 5.v)])); } 
/// Navigates to the gVenliAlanSayfasALRMenScreen when the action is triggered.
onTapPreviousOne(BuildContext context) { NavigatorService.pushNamed(AppRoutes.gVenliAlanSayfasALRMenScreen, ); } 
/// Navigates to the homeScreen when the action is triggered.
onTapLogo(BuildContext context) { NavigatorService.pushNamed(AppRoutes.homeScreen, ); } 

/// Displays a dialog with the [KiIEkleBaArLDialog] content.
onTapKaydet(BuildContext context) { showDialog(context: context, builder: (_) => AlertDialog(content: KiIEkleBaArLDialog.builder(context),backgroundColor: Colors.transparent, contentPadding: EdgeInsets.zero, insetPadding: const EdgeInsets.only(left: 0),)); } 
/// Navigates to the homeScreen when the action is triggered.
onTapImgSuccess(BuildContext context) { NavigatorService.pushNamed(AppRoutes.homeScreen, ); } 
 }
